changes

diff --git a/source/usr/bin/mirrorshuttle-cron b/source/usr/bin/mirrorshuttle-cron
--- a/source/usr/bin/mirrorshuttle-cron
+++ b/source/usr/bin/mirrorshuttle-cron
@@ -1,3 +1,129 @@
 #!/bin/bash
+#
+# Copyright Derek Macias (parts of code from NUT package)
+# Copyright macester (parts of code from NUT package)
+# Copyright gfjardim (parts of code from NUT package)
+# Copyright SimonF (parts of code from NUT package)
+# Copyright Lime Technology (any and all other parts of Unraid)
+#
+# Copyright desertwitch (as author and maintainer of this file)
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License 2
+# as published by the Free Software Foundation.
+#
+# The above copyright notice and this permission notice shall be
+# included in all copies or substantial portions of the Software.
+#
+NOTIFY_BIN="/usr/local/emhttp/plugins/dynamix/scripts/notify"
+HOST=$(echo "$HOSTNAME" | awk '{print toupper($0)}')
+EVENT="MirrorShuttle"
+SUBJECT="[${HOST}] MirrorShuttle:"
+
+if [ ! -r "/boot/config/plugins/mirsht/mirsht.cfg" ]; then
+    echo "configuration file cannot be read; exiting" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Failure" -d "The scheduled moving has failed (unreadable plugin configuration)." -i "alert"
+    exit 0
+fi
+
+# shellcheck disable=SC1091
+source "/boot/config/plugins/mirsht/mirsht.cfg"
+
+if [ "$MOVERSTART" == "enable" ] && [ -e "/var/run/mover.pid" ]; then
+    echo "mover is running; exiting" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Failure" -d "The scheduled moving has failed (mover is running)." -i "alert"
+    exit 0
+fi
+
+if [ "$PARITYSTART" == "enable" ] && [ -r "/var/local/emhttp/var.ini" ]; then
+    PARITYPOS=$(grep "mdResyncPos=" < /var/local/emhttp/var.ini | cut -d'"' -f2)
+    if [ -n "$PARITYPOS" ] && [ "$PARITYPOS" -gt 0 ]; then
+        echo "parity operation is running; exiting" | logger -s -t "mirrorshuttle-cron"
+        [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Failure" -d "The scheduled moving has failed (parity operation in progress)." -i "alert"
+        exit 0
+    fi
+fi
+
+echo "move: started" | logger -s -t "mirrorshuttle-cron"
+
+if [ "$STARTNOTIFY" == "enable" ]; then
+    if [ "$INITAFTER" == "enable" ]; then
+        "$NOTIFY_BIN" -e "${EVENT}" -s "Notice ${SUBJECT} Move Started" -d "The scheduled moving (and re-init) has started." -i "warning"
+    else
+        "$NOTIFY_BIN" -e "${EVENT}" -s "Notice ${SUBJECT} Move Started" -d "The scheduled moving has started." -i "warning"
+    fi
+fi
+
+/usr/bin/mirrorshuttle --mode=move --config=/boot/config/plugins/mirsht/config.yaml --json 1>/dev/null 2>/tmp/mirrorshuttle.json
+RET=$?
+
+case "$RET" in
+  0)
+    echo "move: finished (return code: $RET - success)" | logger -s -t "mirrorshuttle-cron"
+
+    # If re-init was also requested, notify of overall success later (so only once).
+    if [ "$FINISHNOTIFY" == "enable" ] && [ "$INITAFTER" != "enable" ]; then
+        "$NOTIFY_BIN" -e "${EVENT}" -s "Notice ${SUBJECT} Move Finished" -d "The scheduled moving has finished with success." -i "normal"
+    fi
+    ;;
+  1)
+    echo "move: finished (return code: $RET - failure)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Move Failure" -d "The scheduled moving has failed with errors." -i "alert"
+    ;;
+  2)
+    echo "move: finished (return code: $RET - partial failure)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Move Partial Failure" -d "The scheduled moving has failed to move all files." -i "alert"
+    ;;
+  4)
+    echo "move: finished (return code: $RET - invalid configuration)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Move Failure" -d "The scheduled moving has failed due to an invalid configuration." -i "alert"
+    ;;
+  *)
+    echo "move: finished (return code: $RET - unexpected return code)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Move Failure" -d "The scheduled moving has failed with an unexpected return code." -i "alert"
+    ;;
+esac
+
+sync
+sleep 1
+
+if [ "$RET" -gt 0 ] || [ "$INITAFTER" != "enable" ]; then
+    exit 0
+fi
+
+echo "re-init: started" | logger -s -t "mirrorshuttle-cron"
+
+/usr/bin/mirrorshuttle --mode=init --config=/boot/config/plugins/mirsht/config.yaml --json 1>/dev/null 2>>/tmp/mirrorshuttle.json
+RET=$?
+
+case "$RET" in
+  0)
+    echo "re-init: finished (return code: $RET - success)" | logger -s -t "mirrorshuttle-cron"
+    [ "$FINISHNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Notice ${SUBJECT} Move Finished" -d "The scheduled moving (and re-init) has finished with success." -i "normal"
+    ;;
+  1)
+    echo "re-init: finished (return code: $RET - failure)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Re-Init Failure" -d "The scheduled moving's re-init has failed with errors." -i "alert"
+    ;;
+  2)
+    echo "re-init: finished (return code: $RET - partial failure)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Re-Init Partial Failure" -d "The scheduled moving's re-init has failed to move all files." -i "alert"
+    ;;
+  3)
+    echo "re-init: finished (return code: $RET - unmoved files in mirror)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Re-Init Failure" -d "The scheduled moving's re-init has failed due to unmoved files in the mirror." -i "alert"
+    ;;
+  4)
+    echo "re-init: finished (return code: $RET - invalid configuration)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Re-Init Failure" -d "The scheduled moving's re-init has failed due to an invalid configuration." -i "alert"
+    ;;
+  *)
+    echo "re-init: finished (return code: $RET - unexpected return code)" | logger -s -t "mirrorshuttle-cron"
+    [ "$ERRORNOTIFY" == "enable" ] && "$NOTIFY_BIN" -e "${EVENT}" -s "Alert ${SUBJECT} Re-Init Failure" -d "The scheduled moving's re-init has failed with an unexpected return code." -i "alert"
+    ;;
+esac
+
+sync
+sleep 1
 
 exit 0
